app_launcher_cmd = "fuzzel"
truncate_title_after_length = 150

[modules]
left = ["AppLauncher", "Workspaces", "Updates"]
center = ["WindowTitle"]
right = ["Tray", ["Clock", "Settings"]]
[updates]
check_cmd = "pacman -Qu"
update_cmd = 'kitty -e bash -c "sudo pacman -Syu; echo Done - Press enter to exit; read" &'

[workspaces]
visibility_mode = "MonitorSpecific"
enable_workspace_filling = false

[system]
[system.cpu]
warn_threshold = 60
alert_threshold = 80 
[system.mem]
warn_threshold = 70
alert_threshold = 85
[system.temp]
warn_threshold = 60
alert_threshold = 80

[clock]
# clock format see: https://docs.rs/chrono/latest/chrono/format/strftime/index.html
format =  "%A, %b %d – %R" 

[mediaPlayer]
max_title_length = 100

[settings]
lock_cmd = "hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman-manager"

[appearance]
primary_color = "#a9b665"
secondary_color = "#2a2b28"
success_color = "#6c782e"
danger_color = "#c14a4a"
text_color = "#cdc5a4"
workspace_colors = [ "#a9b665"]
special_workspace_colors = [ "#a9b665"]
opacity = 0.8

[appearance.background_color]
base = "#1d2021" 
weak = "#2f302d" 
strong = "#3F3F38" 

[appearance.menu]
opacity = 0.8
